name = "airtable-worker"
compatibility_date = "2023-01-01"
node_compat = true
main = "src/index.js"
# compatibility_flags = [ "nodejs_compat"  ]

[observability]
enabled = true

[env.production]
[env.production.vars]
ENVIRONMENT='production'
NETWORK='mainnet'
FIREWALL='FALSE'
FACTORY_CONTRACT_ID=''
AIRTABLE_BASE_ID='appQsBhe43rrhfa6S'
AGENDA_EXPIRATION='2024-10-02T16:11:14.294Z'
ALERTS_EXPIRATION='2024-10-02T16:11:14.671Z'
AGENDA_TABLE_ID='tblSzutUhYBOnYFC1'
ALERTS_TABLE_ID='tblQUiJAARw6ns18Q'
AGENDA_WEBHOOK_ID='achDNenHlwL29R3Ip'
ALERTS_WEBHOOK_ID='achSNTl1eAMW5c52Z'
enabled = true 
[env.production.triggers]
crons = ["0 0 * * *"]  # Every day at midnight

[env.dev]
[env.dev.vars]
ENVIRONMENT='development'
NETWORK='testnet'
FIREWALL='FALSE'
FACTORY_CONTRACT_ID='1729793502797-factory.testnet'

AIRTABLE_AGENDA_ALERTS_BASE_ID='appYz1vUD2mGO0GZE'
AIRTABLE_ATTENDEE_BASE_ID='appQsBhe43rrhfa6S'

AGENDA_VIEW_NAME='Benji Reminders'
AGENDA_TABLE_NAME='Agenda'
AGENDA_QUERY_FIELDS='Session Name,Confirmed Speakers,Confirmed Moderators,Location,Description,Format,Topic,⚙️ Start Time,⚙️ End Time,Reminder'

ALERTS_VIEW_NAME='Grid view'
ALERTS_TABLE_NAME='Alerts'
ALERTS_QUERY_FIELDS='Title,Description,Custom Link Title,Redirects To,Duration (minutes)'

ATTENDEE_VIEW_NAME='Grid view - Applied to Attend'
ATTENDEE_TABLE_NAME='Applied to Attend'

AGENDA_WEBHOOK_ID='achjtcaaiegOmOjwN'
ALERTS_WEBHOOK_ID='achHcHcWEqDNIRlgS'
AGENDA_EXPIRATION='2024-11-01T00:53:03.727Z'
ALERTS_EXPIRATION='2024-11-01T00:53:04.488Z'
enabled = true 
[env.dev.triggers]
crons = ["0 0 * * *"]  # Every day at midnight
