name = "airtable-worker"
compatibility_date = "2023-01-01"
node_compat = true
# compatibility_flags = [ "nodejs_compat"  ]

[env.production]
[env.production.vars]
ENVIRONMENT="production"
WORKER_URL='https://stripe-worker-production.keypom.workers.dev'
NETWORK='mainnet'
WORKER_ACCOUNT_ID='cf-worker.redacted.near'
FIREWALL="FALSE"

[env.dev]
[env.dev.vars]
ENVIRONMENT="development"
NETWORK='testnet'
FIREWALL="FALSE"
FACTORY_CONTRACT_ID='1725468273999-factory.testnet'
AIRTABLE_BASE_ID='appQsBhe43rrhfa6S'
AGENDA_WEBHOOK_ID = "achaO3Rx6UXslKxao"
ALERTS_WEBHOOK_ID = "achGcCWA18bVn0xxX"
